Support for linux-arm64 platform
BSI-OFIQ/OFIQ-Project pull request #45
Opened 2024-08-07 12:51 UTC by arnowillig

Right now the project is limited to Windows, Mac (X64 and Apple Silicon) and Linux (X64) platforms.

This patch allows the project to be built on Ubuntu running on a Mac with Apple Silicon. (Platform ARM64 / AARCH64).
It would probably also allow this to be built on a Raspberry Pi 4 / 5 with ARM64 platform.

To build call:
`sh build.sh --os linux-arm64`

2024-08-07 16:06 UTC, arnowillig commented on scripts/build.sh
The line `download=OFF` is not necessary.

2024-08-13 13:26 UTC, bbtams commented
Dear Arno, thank you for your contribution. We need some time to test compatibility of your modifications with ARM platforms. Best regards, Benjamin

2025-01-23 12:01 UTC, bbtams requested changes
Dear Arno, thank you for your contribution. With your changes I successfully compiled on a Raspberry pi 4 with Ubuntu 24.04. Yet, the command
$ cd /path/to/OFIQ-Project/scripts/
$ sh conformance_tests.sh
do not run successfully (obviously because of the path 'build/build_linux_arm64' not being considered in conformance_tests.sh). Kindly, can you adjust conformance_tests.sh so that it checks for  an argument "--os linux-arm64" and cds into that building folder on conformance testing? Furthermore, the documentation BUILD.md must adjusted describing the building process for arm64.

2025-01-23 12:10 UTC, bbtams commented
Alternatively, you could set the build/build_linux folder (not build/build_linux_arm64) folder. This would make compilation for arm-based Ubuntu the same as for x86 architectures. I would prefer that approach.

2025-04-11 11:24 UTC, bbtams commented
Dear Arno, we adopted your contribution in the PR #68 which contains support for linux-arm64 and also ensures successful conformance tests etc.. Therefore, we formally reject your PR but acknowledge your contribution.

2025-04-11 11:24 UTC, closed without merging